name: pulsar-io-sqs integration tests

on:
  pull_request:
    branches:
      - master
      - branch-*
  push:
    branches:
      - master
      - branch-*

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build
        run: mvn clean package -DskipTests

      - name: test
        run: |
          ./.ci/integrations/start.sh
          mvn clean package -DskipTests
          mvn -Dtest=*IntegrationTest test -DfailIfNoTests=false

      - name: cleanup
        run: ./.ci/integrations/stop.sh
