name: sqs Release

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Login streamnative docker hub
        run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASSWORD }}"
      
      - name: build connector
        run: |
          version=`./scripts/get-project-version/get-project-version.py`
          mvn clean install -DskipTests
          rm -rf pulsar-*
          cp ./target/pulsar-io-sqs-${version}.nar ./
          cp README.md ./pulsar-io-sqs-readme.md
          echo "ls pulsar-*"
          ls pulsar-*
          echo "::set-output name=nar-file::pulsar-io-sqs-${version}.nar"
          echo "::set-output name=readme-file::pulsar-io-sqs-readme.md"

      - name: build and push docker image
        uses: nick-invision/retry@v2
        with:
          max_attempts: 99
          retry_wait_seconds: 60
          command: |
            PULSAR_VERSION=`./scripts/get-project-version/get-project-version.py`
            REPO=`mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec 2>/dev/null`
            IMAGE_REPO=streamnative/${REPO}
            RUNNER_IMAGE=streamnative/pulsar-functions-java-runner:${PULSAR_VERSION}
            docker pull ${RUNNER_IMAGE}
            docker build --build-arg PULSAR_VERSION="$PULSAR_VERSION" -t ${IMAGE_REPO}:${PULSAR_VERSION} -f ./image/Dockerfile ./
            docker push ${IMAGE_REPO}:${PULSAR_VERSION}
