name: pulsar-io-sqs unit tests

on:
  pull_request:
    branches:
      - master
      - branch-*
  push:
    branches:
      - master
      - branch-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: License check
        run: mvn license:check

      - name: Build with Maven skipTests
        run: mvn clean install -DskipTests

      - name: Style check
        run: mvn checkstyle:check

      - name: Spotbugs check
        run: mvn spotbugs:check

      - name: test after build
        run: mvn -Dtest=SQSConnectorConfigTest test -DfailIfNoTests=false
