version: "2.4"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      HOSTNAME_EXTERNAL: 192.168.1.3
    ports:
      - 4566:4566
  pulsar:
    image: apachepulsar/pulsar-standalone:latest
    ports:
      - 8080:8080
      - 6650:6650
    volumes:
      - ../../:/pulsar-io-sqs